export const directoryActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  DELETE_WINES_START: "DELETE_WINES_START",
  DELETE_WINES_SUCCESS: "DELETE_WINES_SUCCESS",
  DELETE_WINES_FAILURE: "DELETE_WINES_FAILURE",
  ADD_WINES_START: "ADD_WINES_START",
  ADD_WINES_SUCCESS: "ADD_WINES_SUCCESS",
  ADD_WINES_FAILURE: "ADD_WINES_FAILURE"
};
