export const ordersActionTypes = {
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
  FETCH_CURRENT_USER_ORDERS_START: "FETCH_CURRENT_USER_ORDERS_START",
  FETCH_CURRENT_USER_ORDERS_SUCCESS: "FETCH_CURRENT_USER_ORDERS_SUCCESS",
  FETCH_CURRENT_USER_ORDERS_FAILURE: "FETCH_CURRENT_USER_ORDERS_FAILURE",
};
