export const ordersActionTypes = {
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
  FETCH_CURRENT_USER_ORDERS_START: "FETCH_CURRENT_USER_ORDERS_START",
  FETCH_CURRENT_USER_ORDERS_SUCCESS: "FETCH_CURRENT_USER_ORDERS_SUCCESS",
  FETCH_CURRENT_USER_ORDERS_FAILURE: "FETCH_CURRENT_USER_ORDERS_FAILURE",
  SORT_ALL_ORDERS_BY_SELECT: "SORT_ALL_ORDERS_BY_SELECT",
};
